### ISSUE TITLE
Treatment of blank lines in Sort/Invert options

### ISSUE THREAD

**Issue by Ste1io** [carlocardella/vscode-TextToolbox#28]
Invert and sort treat blank lines differently when dealing with blank lines. Invert does a 1-for-1 line order inversion regardless of line data,. Sort reorders the lines, and additionally removes blank lines, when I would expect blank lines to simply be moved to one end based on the sorting strategy.

I would argue that removing blank lines is unexpected behavior in a sort function. It may be convenient at times, but that would qualify it as a "sort & filter" option, not a sort option. More times than not, in my work, it's important that the line count remain unchanged when doing a line sort, even if it contains blank lines, especially when I'm copying a multi-line selection with a few thousand cursor instances into another document with (presumably) an equal number of multi-line cursor instances. 😆 

(Sorry to flood you with issues all at once here; I felt this was best as a separate issue from #26 given that it's related to the user experience and consistency/predictability in how sorting options behave, not an actual bug like the other.)

Thanks again for such a great plugin and responsiveness; it's one of my must-haves, and one of the only ones I've taken the time to go through the hassle of rating in the marketplace. Keep up the excellent work.

**Comment by carlocardella** [comment]
6376d7519ddd339728752e6da86cebd91d866a6a

Pre-release 2.10.5 should be available in the Marketplace shortly

**Comment by Ste1io** [comment]
Pre-release 2.10.5 working perfect @carlocardella

**Comment by carlocardella** [comment]
Thanks, I'll publish a stable release with these fixes later today
