### ISSUE TITLE
Incorrect transformation to Kebab 

### ISSUE THREAD

**Issue by JustPilz** [carlocardella/vscode-TextToolbox#34]
`TextToolbox` to kebab-case

Expected behavior:
`text-toolbox`

Actual behavior:
`texttoolbox`

**Comment by carlocardella** [comment]
Transform to snake case shows the same behavior. 

Quickly tested with a few sample strings; also, found VSCode has builtin commands for kebab and snake case transformations:

![image](https://user-images.githubusercontent.com/5784415/212932670-e1f04167-3e95-4fd2-a8ed-b93868899816.png)

Just a couple of observations:

1. TextToolbox properly transform strings with a space between words but fails to transform PascalCase strings.
2. The builtin VSCode commands show the opposite behavior: they properly transform PascalCase strings but fail to transform strings with space separators.

**Comment by carlocardella** [comment]
Just published 2.12.0, the extension can now handle both points described in my previous comment
