### ISSUE TITLE
Insert Random with multi-line editing

### ISSUE THREAD

**Issue by Ste1io** [carlocardella/vscode-TextToolbox#39]
When multiple cursor selections are present, the "Insert Random..." options insert the same random value at each location. Could there be an additional prompt to choose between using a single random value for all cursor locations (current default behavior), or inserting a different random option for each cursor location? The extra prompt step would ideally only appear if multiple cursor instances are present.

![Code_usDFTxutTZ](https://user-images.githubusercontent.com/37424493/215277647-862606c8-ca4d-4a27-80e1-b93f582d7ac1.gif)

**Comment by carlocardella** [comment]
Good suggestion, I'll add it

**Comment by carlocardella** [comment]
031fc946f8561e016cc633e1659127c3f4e0504e

![insert random ip](https://user-images.githubusercontent.com/5784415/215370083-59ae6ca1-c017-4cf9-8bd2-7cd5369e0e85.gif)
